### ISSUE TITLE
bug when importing the affix "lucky hit up to a chance to make enemies vulnerable for seconds"

### ISSUE THREAD

**Issue by pedrogab96** [jeydo/diablo4LootFilterProfileBuilder#1]
Bug when importing the affix "lucky hit up to a chance to make enemies vulnerable for seconds" on the Heartseeker build ring from Maxroll.

Build link: https://maxroll.gg/d4/planner/yi5n10wr#3

The name of the imported affix came out different than expected:

Expected affix:
lucky_hit_up_to_a_chance_to_make_enemies_vulnerable_for_seconds

Returned affix from the import:
lucky_hit:_up_to_a__chance_to_make_enemies_vulnerable_for__seconds

**Comment by jeydo** [comment]
I just made an update and it's fixed
